### PR TITLE
Don't monkeypatch the CatalogController. Fixes #49

### LINKED ISSUE #49: Using BlacklightAdvanceSearch makes I18n unavailable in CatalogController
Due to this block causing CatalogController to load before the I18n initializers have run:
https://github.com/projectblacklight/blacklight_advanced_search/blob/master/lib/blacklight_advanced_search/engine.rb#L16-L21

This is the same as https://github.com/projectblacklight/blacklight_range_limit/issues/41 but in the AdvanceSearch this time.

### PR DESCRIPTION
**Pull request by jcoyne**
This depends on
https://github.com/projectblacklight/blacklight/pull/1374

### CODE REVIEW

**Comment by tampakis** [comment]
Can someone merge this and cut a new gem release?

**Comment by tampakis** [comment]
@cbeer? @cjcolvar?

**Comment by jcoyne** [comment]
@tampakis 6.0.1 is out

**Comment by tampakis** [comment]
@jcoyne++

**Comment by cbeer** [comment]
Was this really a patch-level change (and, should we actually pin to `blacklight >= 6.0.1, ~> 6.0`?

**Comment by jcoyne** [comment]
Sorry, it was a bug for me. Want me to yank 6.0.1?

**Pull request merged**
